Improved: code to hide option to set baseURL if value available in '.env' file (#29wgkkh).
hotwax/receiving pull request #103
Opened 2022-05-16 11:26 UTC by Mayank909

### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/receiving#contribution-guideline)

2022-05-18 06:25 UTC, adityasharma7 requested changes

2022-05-18 06:25 UTC, adityasharma7 commented on src/api/index.ts
> +        baseURL = store.getters['user/getInstaceUrl'];
```suggestion
        baseURL = store.getters['user/getInstanceUrl'];
```

2022-05-18 06:26 UTC, adityasharma7 commented on src/views/Login.vue
> +     if(!this.baseURL) this.store.dispatch("user/setUserInstanceUrl", this.instanceUrl.trim())
Indentation issues

2022-05-18 08:06 UTC, Mayank909 commented on src/views/Login.vue
> +     if(!this.baseURL) this.store.dispatch("user/setUserInstanceUrl", this.instanceUrl.trim())
Done Sir

2022-05-18 08:07 UTC, Mayank909 commented on src/api/index.ts
> +        baseURL = store.getters['user/getInstaceUrl'];
Done Sir

2022-07-15 10:17 UTC, adityasharma7 approved these changes

2022-07-15 10:18 UTC, merged