Fixed: Logic to recieveAll returns on return-details page(#2t2wcjr)
hotwax/receiving pull request #130
Opened 2022-09-23 05:38 UTC by shashwatbangar

### Related Issues

Closes #

### Short Description and Why It's Useful

When we want to receive all return shipments, we always will get one item, so its unnecessary to use filter and loop over whole current items array. So we will use find here so as soon as we meet the condition, it returns without looping over array.

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/receiving#contribution-guideline)

2022-09-23 07:41 UTC, adityasharma7 requested changes

2022-09-23 07:41 UTC, adityasharma7 commented on src/views/ReturnDetails.vue
> +      await this.store.dispatch('return/receiveReturn', {payload: this.current});
I think we should handle for the error

2022-09-23 07:41 UTC, adityasharma7 commented on src/views/ReturnDetails.vue
> +      this.current.items.find((ele: any) => {
I think we should find the element and store it in a variable, then update it

2022-09-23 07:53 UTC, shashwatbangar commented on src/views/ReturnDetails.vue
> +      await this.store.dispatch('return/receiveReturn', {payload: this.current});
done sir

2023-02-01 13:15 UTC, adityasharma7 requested changes

2023-02-01 13:15 UTC, adityasharma7 commented on src/views/ReturnDetails.vue
> +          element.quantityAccepted = ele.quantityOrdered;
I think this will not work, we are updating element which is not defined

2023-02-02 12:36 UTC, merged