Fixed: UI of returnDetails page(#2v7gpv1)
hotwax/receiving pull request #138
Opened 2022-09-27 06:49 UTC by shashwatbangar

### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/receiving#contribution-guideline)

2022-09-27 12:15 UTC, dt2patel requested changes
remove commented code

2022-09-27 12:15 UTC, dt2patel commented on src/views/PurchaseOrderDetail.vue
> +/* .po-meta {
need to delete commented styles

2022-09-27 12:15 UTC, dt2patel commented on src/views/ReturnDetails.vue
> +      <!-- <div> -->
delete commented div

2022-09-27 13:24 UTC, shashwatbangar commented on src/views/PurchaseOrderDetail.vue
> +/* .po-meta {
Done sir

2022-09-28 06:46 UTC, dt2patel approved these changes

2022-09-28 06:46 UTC, merged