Added: Copy order id to clipboard
hotwax/receiving pull request #157
Opened 2022-10-14 21:43 UTC by franciscoemanuel

### Related Issues
Closes #153

### Short Description and Why It's Useful

- Adds copy icon on order id chip of PurchaseOrderDetail
- Uses @capacitor plugin to copy to clipboard

### Screenshots of Visual Changes before/after (If There Are Any)
![image](https://user-images.githubusercontent.com/15387723/195948478-8e1dc559-c94f-4714-a924-3704b92e0f28.png)

**IMPORTANT NOTICE** - Remember to add changelog entry
Did not found how I could have done that, if instructions are provided I'd be welcome

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/receiving#contribution-guideline)

2022-10-16 06:04 UTC, adityasharma7 commented
Thanks for your contribution @franciscoemanuel 

I would suggest having a common method with success message and reusing it across the app

A good reference
https://github.com/hotwax/bopis/blob/develop/src/views/OrderDetail.vue#L98
https://github.com/hotwax/bopis/blob/develop/src/utils/index.ts#L22

This way we would be able to reuse the code and maintain easily

WDYT?

2022-10-16 18:12 UTC, franciscoemanuel commented
@adityasharma7 for sure, if you cold take a second look please.

2022-10-17 04:18 UTC, ymaheshwari1 requested changes

2022-10-17 04:18 UTC, ymaheshwari1 commented on src/utils/index.ts
> +    const { Clipboard } = Plugins;
Hi, please improve the indentation to 2 spaces for consistency.

2022-10-17 05:17 UTC, ymaheshwari1 approved these changes

2022-10-17 05:20 UTC, adityasharma7 commented on src/views/PurchaseOrderDetail.vue
> +            <ion-chip @click="copyOrderIdToClipboard">{{ order.orderId }}<ion-icon :icon="copy"/></ion-chip>
```suggestion
            <ion-chip @click="copyOrderIdToClipboard">{{ order.orderId }}<ion-icon :icon="copy-outline"/></ion-chip>
```

2022-10-17 06:02 UTC, merged

2022-10-17 06:02 UTC, adityasharma7 commented
Thanks is merged. Thanks @franciscoemanuel for your contribution!