Implemented: showing receiving history upon clicking on shipment item 'received' chip (#85zrhcn67)
hotwax/receiving pull request #174
Opened 2023-01-04 12:40 UTC by k2maan

### Related Issues

Closes #151 

### Short Description and Why It's Useful

Upon clicking the 'received' chip on the PO details page, the receiving history of that shipment item will be shown in the modal.

### Screenshots of Visual Changes before/after (If There Are Any)

https://user-images.githubusercontent.com/59442907/210532465-9f04b53b-5d8e-4da9-943e-1464286570e8.webm

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/receiving#contribution-guideline)

2023-01-04 12:45 UTC, ymaheshwari1 requested changes

2023-01-04 12:45 UTC, ymaheshwari1 commented on src/views/PurchaseOrderDetail.vue
> +    async receivingHistory(productId?: any) {
```suggestion
    async receivingHistory(productId?: string) {
```

2023-01-05 11:02 UTC, ymaheshwari1 approved these changes

2023-01-06 10:41 UTC, adityasharma7 approved these changes

2023-01-06 10:41 UTC, merged