Implemented: Migrated from moment timezone to luxon(#2dewerv)
hotwax/receiving pull request #179
Opened 2023-01-10 13:30 UTC by shashwatbangar

### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/receiving#contribution-guideline)

2023-01-17 06:05 UTC, disha1202 requested changes

2023-01-17 06:05 UTC, disha1202 commented on src/utils/index.ts
> +  const dateTime = DateTime.fromISO(dateTimeValue, { setZone: true}).toFormat("yyyy-MM-dd'T'HH:mm:ss")
```suggestion
  const dateTime = DateTime.fromISO(dateTimeValue, { zone: 'utc' }).toFormat("yyyy-MM-dd'T'HH:mm:ss")
```

2023-01-17 06:10 UTC, shashwatbangar commented on src/utils/index.ts
> +  const dateTime = DateTime.fromISO(dateTimeValue, { setZone: true}).toFormat("yyyy-MM-dd'T'HH:mm:ss")
Done.

2023-01-19 07:12 UTC, adityasharma7 requested changes

2023-01-19 07:12 UTC, adityasharma7 commented on package.json
>      "moment": "^2.29.1",
I think we should remove moment related dependencies

2023-01-19 07:12 UTC, adityasharma7 commented on src/store/modules/user/actions.ts
> +      const localTimeZone = DateTime.now().zoneName;
We haven't set the default Luxon timezone
`Settings.defaultZone = this.userProfile.userTimeZone;`

2023-01-19 07:12 UTC, adityasharma7 commented on src/store/modules/user/actions.ts
> +      const localTimeZone = DateTime.now().zoneName;
Also, when we are setting the timezone
https://github.com/hotwax/receiving/pull/179/files#diff-d3c10a6ece79180d52468851ebe745d66365adafc59ee774a50b5687b3d42ff6R128

2023-01-19 07:20 UTC, adityasharma7 requested changes

2023-01-19 07:20 UTC, adityasharma7 commented on src/store/modules/user/actions.ts
>          emitter.emit('timeZoneDifferent', { profileTimeZone: resp.data.userTimeZone, localTimeZone});
We should remove feature to show timezone different alert

2023-01-19 07:21 UTC, adityasharma7 commented
It seems we do have support to change timezone in this app, please add support for it

2023-01-30 12:12 UTC, merged