implemented: logic to fetch receivers details(#85zrnfjuc)
hotwax/receiving pull request #200
Opened 2023-02-21 07:11 UTC by disha1202

### Related Issues

Closes #98 

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/receiving#contribution-guideline)

2023-02-21 10:00 UTC, k2maan commented on src/services/OrderService.ts
> +const getReceiversDetails = async (payload: any): Promise<any> => {
```suggestion
const getReceiverDetails = async (payload: any): Promise<any> => {
```

2023-02-21 10:01 UTC, k2maan commented on src/store/modules/order/OrderState.ts
> +  receiversDetails: any;
```suggestion
  receiverDetails: any;
```

2023-02-22 10:36 UTC, k2maan approved these changes

2023-02-22 10:42 UTC, k2maan commented
We can have a discussion over the naming convention for variables with the word `receivers` in them.

2023-02-24 06:09 UTC, adityasharma7 requested changes

2023-02-24 06:09 UTC, adityasharma7 commented on src/store/modules/order/index.ts
> +      receiversDetails: {},
namesByUserLogin

2023-02-24 06:09 UTC, adityasharma7 commented on src/store/modules/order/mutations.ts
> +      state.receiversDetails[receiversLoginId] = receiversDetails[receiversLoginId];
Why not spread?

2023-03-28 06:37 UTC, adityasharma7 approved these changes

2023-03-28 07:29 UTC, merged