Implemented: functionality which allows users to manually close purchase order items when they receive them. (#212)
hotwax/receiving pull request #258
Opened 2023-08-29 07:15 UTC by amansinghbais

### Related Issues

Closes #212

### Short Description and Why It's Useful

Users can currently only receive inventory for purchase orders; there is no manual control for users to close the PO items. When the promise date arrives, the PO automatically expires. Here implemented a feature where users can close all or some shipments at once.

- Created a footer for purchase order page with two buttons "Receive" and "Receive and Close"
      - Receive button create shipments for the items whom quantities are changed.
      - Receive and Close button create shipments and then close the items which are selected from the "closePurchaseOrder" modal.
-   Created a modal "closePurchaseOrder" modal which allows users to select the items they want to close or select all the items at once.
- Created a new alert for close purchase order items.
- Implemented an api "changeOrderItemStatus" in OrderService which is called to close shipment items or purchase order. It takes some item details as payload.

### Screenshots of Visual Changes before/after (If There Are Any)

Before
![Screenshot from 2023-08-29 12-25-55](https://github.com/hotwax/receiving/assets/69574321/2ac2cad0-04c9-47e7-865a-269273ad5e37)

After 

![Screenshot from 2023-08-29 12-26-35](https://github.com/hotwax/receiving/assets/69574321/fca1c0da-f7d2-4fbb-b135-7c241af78b93)
![Screenshot from 2023-08-29 12-31-57](https://github.com/hotwax/receiving/assets/69574321/d0b1af0b-71ed-4e46-ac04-9997b57a9646)
![Screenshot from 2023-08-29 12-27-06](https://github.com/hotwax/receiving/assets/69574321/b03e007f-5657-44d6-9e88-e286e44de4de)
![Screenshot from 2023-08-29 12-27-12](https://github.com/hotwax/receiving/assets/69574321/4fb06e41-8e20-42bb-8e6b-b6b16051d4d8)
![Screenshot from 2023-08-29 12-27-36](https://github.com/hotwax/receiving/assets/69574321/8f75c22e-9e9a-4373-8e88-461454f4896e)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/receiving#contribution-guideline)

2023-09-08 06:14 UTC, ymaheshwari1 requested changes

2023-09-08 06:14 UTC, ymaheshwari1 commented on src/services/OrderService.ts
> +    url: "/changeOrderItemStatus",
```suggestion
    url: "service/changeOrderItemStatus",
```

2023-09-08 06:14 UTC, ymaheshwari1 commented on src/views/PurchaseOrderDetail.vue
> +import closePurchaseOrderModal from '@/views/closePurchaseOrderModal.vue'
Follow correct naming convention for view.

2023-09-08 06:45 UTC, k2maan requested changes

2023-09-15 10:29 UTC, k2maan requested changes

2023-09-18 12:15 UTC, k2maan requested changes

2023-09-20 06:17 UTC, k2maan requested changes

2023-09-20 06:17 UTC, k2maan commented on src/views/ClosePurchaseOrderModal.vue
> +            this.updatePOItemStatus()
```suggestion
            await this.updatePOItemStatus()
```

2023-09-20 06:17 UTC, k2maan commented on src/views/ClosePurchaseOrderModal.vue
> +          showToast(translate("Purchase order update failed. Verify your internet connection and retry."))
```suggestion
          showToast(translate("Purchase order update failed."))
```

2023-09-20 06:17 UTC, k2maan commented on src/views/ClosePurchaseOrderModal.vue
> +        .catch((err)=>{
We can follow try-catch syntax and also show toast in case of success.

2023-09-20 06:18 UTC, k2maan requested changes

2023-09-20 06:18 UTC, k2maan commented on src/views/ClosePurchaseOrderModal.vue
> +  props: ['createShipment', 'isEligibileForCreatingShipment'],
Instead of passing functions as props, we should use emitter as passing function props is an anti-pattern in Vue.

2023-10-10 06:00 UTC, k2maan requested changes

2023-10-12 04:40 UTC, k2maan requested changes

2023-10-12 04:40 UTC, k2maan commented on src/views/ClosePurchaseOrderModal.vue
> +      const failedItemsCount = eligibleItems.filter((item: any) => item.statusUpdated === false).length
Find a better alternative than using the additional statusUpdated variable.

2023-10-17 13:25 UTC, k2maan approved these changes

2023-10-18 05:24 UTC, ymaheshwari1 requested changes

2023-10-18 05:24 UTC, ymaheshwari1 commented on src/views/ClosePurchaseOrderModal.vue
> +            this.router.push('/purchase-orders')
Why are we changing the route from here and also changing the same from the createShipment method?

2023-10-18 05:24 UTC, ymaheshwari1 commented on src/views/ClosePurchaseOrderModal.vue
> +      const eligibleItems = this.order.items.filter((item: any) => item.isChecked)
If the item is already rejected or completed but if the isChecked property is true for that item then the item will again be included in the eligibleItems list.

2023-10-18 05:58 UTC, amansinghbais commented on src/views/PurchaseOrderDetail.vue
> +        componentProps: {
In some cases, we need to close a PO item without creating shipment, hence this property is needed.

2023-10-18 09:39 UTC, ymaheshwari1 requested changes

2023-10-18 13:02 UTC, ymaheshwari1 requested changes

2023-10-18 13:09 UTC, ymaheshwari1 approved these changes

2023-10-20 13:28 UTC, merged