Improved: enhanced visibility of completed items in POs and displayed items count (#259)
hotwax/receiving pull request #260
Opened 2023-09-08 10:14 UTC by amansinghbais

### Related Issues

Closes #259
Closes #152

### Short Description and Why It's Useful

Currently completed items on the Purchase Order detail page are not clearly distinguishable from pending items which doesn't allows users quickly identify which products are no longer outstanding. This feature is crucial for users dealing with large and complex POs. Hence,
- Written code to display completed items too on the POs detail page.
- Written a function and added few template items so as to clearly display total orders count, pending items count, and completed items count.

### Screenshots of Visual Changes before/after (If There Are Any)

Before
![Screenshot from 2023-09-08 15-19-14](https://github.com/hotwax/receiving/assets/69574321/56ba17f1-c4a7-4f9c-bac7-288a85e3975f)

After
![Screenshot from 2023-09-08 15-19-32](https://github.com/hotwax/receiving/assets/69574321/be63b3ba-a9ed-429c-8900-379f780eb4ae)

![Screenshot from 2023-09-08 15-19-38](https://github.com/hotwax/receiving/assets/69574321/6bbe9a50-7b10-4b02-a7e1-55d33a85f38c)

![Screenshot from 2023-09-08 15-19-52](https://github.com/hotwax/receiving/assets/69574321/5e8bb4e3-0fad-4bdc-974a-741b3647a3b9)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/receiving#contribution-guideline)

2023-09-13 13:08 UTC, k2maan requested changes

2023-09-13 13:08 UTC, k2maan commented on src/views/PurchaseOrderDetail.vue
> +                <ion-badge color="medium" class="ion-margin-end">{{ item.quantity }} {{ $t("ordered") }}</ion-badge>
Use slots instead of float styling and margin.

2023-09-15 07:16 UTC, k2maan approved these changes

2023-09-15 10:10 UTC, ymaheshwari1 commented on src/views/PurchaseOrderDetail.vue
> +      } else if(orderType === 'pending') {
```suggestion
      } else {
```

We can remove this `if` as there is no other case we are handling for orderType.

2023-09-18 09:13 UTC, ymaheshwari1 requested changes

2023-09-18 09:13 UTC, ymaheshwari1 commented on src/views/PurchaseOrderDetail.vue
> +          </ion-text>
```suggestion
          <ion-text v-if="getPOItemsCount('completed') > 1" color="medium" class="ion-margin-end">
            {{ $t("COMPLETED: ITEMS", { itemsCount: getPOItemsCount('completed')}) }}
          </ion-text>
          <ion-text v-else color="medium" class="ion-margin-end">
            {{ $t("COMPLETED: ITEM", { itemsCount: getPOItemsCount('completed')}) }}
          </ion-text>
```

2023-09-18 09:15 UTC, ymaheshwari1 commented on src/views/PurchaseOrderDetail.vue
> +          <ion-icon v-if="getPOItemsCount('completed') && showCompletedItems" :icon="eyeOutline" @click="showCompletedItems = !showCompletedItems" />
```suggestion
          <ion-icon v-if="getPOItemsCount('completed')" :icon="showCompletedItems ? eyeOutline : eyeOffOutline" @click="showCompletedItems = !showCompletedItems" />
```

2023-09-18 09:19 UTC, ymaheshwari1 commented on src/views/PurchaseOrderDetail.vue
> +    getPOItemsCount(orderType: string) {
We can use a single method for getting the count and items and use `.length` in the template to get the count

2023-09-18 11:21 UTC, ymaheshwari1 approved these changes

2023-10-06 13:47 UTC, merged