Implemented: Added Pointer on Hover for Completed items icon(#271)
hotwax/receiving pull request #286
Opened 2023-12-11 06:14 UTC by shanmukhdutt

(#271 )

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/receiving#contribution-guideline)

2023-12-11 09:18 UTC, k2maan requested changes

2023-12-11 09:18 UTC, k2maan commented on src/views/PurchaseOrderDetail.vue
> +      cursor: pointer;
Improve indentation

2023-12-12 09:28 UTC, k2maan approved these changes

2023-12-13 06:44 UTC, ymaheshwari1 requested changes

2023-12-13 06:44 UTC, ymaheshwari1 commented on src/views/PurchaseOrderDetail.vue
> +            <ion-icon v-if="getPOItems('completed').length" :icon="showCompletedItems ? eyeOutline : eyeOffOutline" />
Move `v-if` condition as well on the button

2023-12-13 10:00 UTC, ymaheshwari1 approved these changes

2023-12-14 05:41 UTC, merged