fixed: Blank header appears on return detail page if ShopifyOrderName and HC OrderID are not present (#399)
hotwax/receiving pull request #405
Opened 2024-10-19 09:13 UTC by ashutosh7i

### Related Issues

#399 

### Short Description and Why It's Useful
When ShopifyOrderName and HC OrderID are missing, the header now displays alternative identifiers External ID. If no such identifiers is available, a placeholder message "Return" is shown ensuring the header is not blank.

### Screenshots of Visual Changes before/after (If There Are Any)

![image](https://github.com/user-attachments/assets/e8f2250b-4518-4733-b1b0-1fde1180bafd)

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/receiving#contribution-guideline)

2024-10-19 16:33 UTC, ymaheshwari1 requested changes
Thanks for the contribution @ashutosh7i .

Please check the comment below, once done this PR will be good to be merged.

2024-10-19 16:33 UTC, ymaheshwari1 commented on src/views/ReturnDetails.vue
> +            <h1> {{ current.shopifyOrderName ? current.shopifyOrderName : current.hcOrderId ? current.hcOrderId : current.externalId ? current.externalId : 'Return' }}</h1>
We need to make the static text internationalize like the one done for `Scan barcodes to receive them` text on line 28.

Also can you make the static text same as the one displayed in title `Return Details`

2024-10-20 14:24 UTC, ashutosh7i commented
Thank you,
i have implemented required changes.

https://github.com/user-attachments/assets/587389f1-4bb7-424f-b2dc-7cc7a4245fb9

2024-10-21 05:09 UTC, ymaheshwari1 approved these changes

2024-10-21 05:10 UTC, merged