Rendered data on the PO Details page ( #1xhkf57 ).
hotwax/receiving pull request #56
Opened 2022-02-15 10:54 UTC by meet-aniket

2022-02-15 11:52 UTC, adityasharma7 requested changes

2022-02-15 11:52 UTC, adityasharma7 commented on src/router/index.ts
> +    path: "/purchase-order-detail/:slug",
Please revert unwanted changes

2022-02-15 11:52 UTC, adityasharma7 commented on src/components/PurchaseOrderItem.vue
> +      const payload = {
I think we should decide in action whether to make an API call or not. We should pass orderId, and in action we decide whether we want extract from existing list or make API call

2022-02-15 11:52 UTC, adityasharma7 commented on src/store/modules/order/actions.ts
> +    if (current.length && current[0]?.doclist && current[0]?.doclist.docs[0].orderId === orderId)
Improve the schema, current should have orderId and other common attribute while items should have complete list with total

2022-02-15 11:52 UTC, adityasharma7 commented on src/store/modules/order/getters.ts
> +  getOrderDetail(state) {
```suggestion
  getCurrent(state) {
```

2022-02-15 11:52 UTC, adityasharma7 commented on src/store/modules/order/mutation-types.ts
> +export const ORDER_PRCHS_DTAIL_UPDATED = SN_ORDER + '/PRCHS_ORDRS_DTAL_UPDATED'
```suggestion
export const ORDER_CURRENT_UPDATED = SN_ORDER + '/PRCHS_CURRENT_UPDATED'
```

2022-02-15 11:52 UTC, adityasharma7 commented on src/views/PurchaseOrderDetail.vue
> +      orderDetail: 'order/getOrderDetail',
```suggestion
      order: 'order/getCurrent',
```

2022-02-15 13:24 UTC, ymaheshwari1 requested changes

2022-02-15 13:24 UTC, ymaheshwari1 commented on src/store/modules/order/actions.ts
> +    if (current.length && current[0]?.orderId === orderId) return current;
```suggestion
    if (current.length && current[0]?.orderId === orderId) { return current }
```

2022-02-15 13:24 UTC, ymaheshwari1 commented on src/store/modules/order/actions.ts
> +        this.dispatch('product/fetchProductInformation', { order: order });
```suggestion
        this.dispatch('product/fetchProductInformation', { order });
```

2022-02-15 13:24 UTC, ymaheshwari1 commented on src/store/modules/order/mutation-types.ts
> +export const ORDER_CURRENT_UPDATED = SN_ORDER + '/PRCHS_CURRENT_UPDATED'
mismatch between mutation names.

2022-02-15 13:37 UTC, adityasharma7 requested changes

2022-02-15 13:37 UTC, adityasharma7 commented on src/store/modules/order/OrderState.ts
> +  current: any
```suggestion
  current: {
    orderId: string;
    externalOrderId: string;
    items: []
  }
```

2022-02-16 06:30 UTC, ymaheshwari1 approved these changes

2022-02-16 06:32 UTC, adityasharma7 approved these changes

2022-02-16 06:32 UTC, merged