Updated order state mutations and actions(#220vhcr)
hotwax/receiving pull request #67
Opened 2022-02-16 12:49 UTC by disha1202

### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/receiving#contribution-guideline)

2022-02-16 15:47 UTC, ymaheshwari1 requested changes

2022-02-16 15:47 UTC, ymaheshwari1 commented on src/store/modules/order/actions.ts
> +          commit(types.ORDER_CURRENT_UPDATED, { orderId : order.doclist.docs[0]?.orderId, externalOrderId: order.doclist.docs[0]?.externalOrderId, order: order.doclist.docs })
```suggestion
          commit(types.ORDER_CURRENT_UPDATED, { orderId : order.doclist.docs[0]?.orderId, externalOrderId: order.doclist.docs[0]?.externalOrderId, items: order.doclist.docs })
```

2022-02-18 07:21 UTC, ymaheshwari1 approved these changes

2022-03-01 07:06 UTC, adityasharma7 requested changes

2022-03-01 07:06 UTC, adityasharma7 commented on src/store/modules/order/mutations.ts
>      if (payload.order) {
We should have only state.current = payload; and avoid having if-else

2022-04-07 06:58 UTC, merged