Fixed: issue related to count of items not updating in shipment list page ( #226j5hb ).
hotwax/receiving pull request #84
Opened 2022-02-28 06:55 UTC by meet-aniket

2022-02-28 08:55 UTC, ymaheshwari1 requested changes

2022-02-28 08:55 UTC, ymaheshwari1 commented on src/views/AddProductModal.vue
> +      this.store.dispatch('shipment/addShipmentItem', product);
Remove this unwanted change.

2022-03-03 08:00 UTC, adityasharma7 requested changes

2022-03-03 08:00 UTC, adityasharma7 commented on src/store/modules/shipment/actions.ts
> +    shipments.map((shipment: any) => {
I think you should find the shipment and update

2022-03-09 05:10 UTC, adityasharma7 approved these changes

2022-03-09 05:17 UTC, ymaheshwari1 approved these changes

2022-03-09 05:36 UTC, merged