Improved code so that clicking on thumbnail of image should open it in a modal (#23301r3)
hotwax/receiving pull request #88
Opened 2022-03-09 08:19 UTC by azkyakhan

…

### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/receiving#contribution-guideline)

2022-03-09 08:26 UTC, azkyakhan commented
https://user-images.githubusercontent.com/82817616/157401922-029ad329-6391-4927-98d9-7c98c980adde.mp4

2022-03-11 05:39 UTC, dt2patel commented
@ymaheshwari1 does this look good to you?

2022-04-06 05:42 UTC, adityasharma7 requested changes

2022-04-06 05:42 UTC, adityasharma7 commented on src/views/PurchaseOrderDetail.vue
> +    async image(imageUrl: string, productName: string) {
```suggestion
    async openImage(imageUrl: string, productName: string) {
```

2022-04-06 05:42 UTC, adityasharma7 commented on src/views/PurchaseOrderDetail.vue
> +      const createmodal = await modalController.create({
```suggestion
      const imageModal = await modalController.create({
```

2022-04-06 05:42 UTC, adityasharma7 commented on src/views/PurchaseOrderDetail.vue
> +        componentProps: {imageUrl , productName}
```suggestion
        componentProps: { imageUrl , productName }
```

2022-04-06 06:14 UTC, ymaheshwari1 approved these changes

2022-04-06 06:14 UTC, azkyakhan commented on src/views/PurchaseOrderDetail.vue
> +    async image(imageUrl: string, productName: string) {
I have replaced method name from `image` with `openImage`.

2022-04-06 06:15 UTC, azkyakhan commented on src/views/PurchaseOrderDetail.vue
> +      const createmodal = await modalController.create({
I have replaced `createmodal` with `imageModal`.

2022-04-06 06:15 UTC, azkyakhan commented on src/views/PurchaseOrderDetail.vue
> +        componentProps: {imageUrl , productName}
I have added space here.

2022-04-06 06:26 UTC, adityasharma7 approved these changes

2022-04-06 06:26 UTC, merged